#!/sbin/busybox sh
#
# z4mod init wrapper, by Elia Yehuda (c) 2010 GPLv2
#
# Loops over partitions to find ext2/3/4 and replace mount command in rc.conf.
# It extracts info from the ext2/3/4 structure to check for type of ext.
#
set -x
(

PATH=/sbin:/system/bin

# setting the variables once
RO_COMPAT=0x464
INCOMPAT=0x460
COMPAT=0x45c
MAGIC=0x438
EXT3_FEATURE_COMPAT_HAS_JOURNAL=4
EXT4_FEATURE_RO_COMPAT_HUGE_FILE=8
EXT4_FEATURE_RO_COMPAT_GDT_CSUM=16
EXT4_FEATURE_RO_COMPAT_DIR_NLINK=32
EXT4_FEATURE_RO_COMPAT_EXTRA_ISIZE=64
EXT4_FEATURE_INCOMPAT_64BIT=128
EXT4_FEATURE_INCOMPAT_MMP=256

# loop on known partitions, and extract information
for part in `busybox ls /dev/block/stl* /dev/block/mmcblk0p*`; do
#for part in /dev/block/stl* /dev/block/mmcblk0p*; do
	# check if this is an ext2/3/4
	magic="`busybox dd if=$part skip=$((MAGIC)) bs=1 count=2 2>/dev/null | busybox od -x | busybox awk '{print $2}'`"
	if [ "${magic}" == "ef53" ]; then 
		# has journal?
		compat=0x"`busybox dd if=$part skip=$((COMPAT)) bs=1 count=4 2>/dev/null | busybox od -X | busybox awk '{print $2}'`"
		if [ "$((compat&=EXT3_FEATURE_COMPAT_HAS_JOURNAL))" == "0" ]; then
			# ext2
			busybox sed -i 's|mount rfs '"${part}"' \([^ ]*\) .*|mount ext2 '"${part}"' \1 nosuid nodev noatime nodiratime errors=continue|g' /*.rc
			FOUND_NON_RFS="true"
		else
			# ext3 or ext4
			ro_compat=0x"`busybox dd if=$part skip=$((RO_COMPAT)) bs=1 count=4 2>/dev/null | busybox od -X | busybox awk '{print $2}'`"
			incompat=0x"`busybox dd if=$part skip=$((INCOMPAT)) bs=1 count=4 2>/dev/null | busybox od -X | busybox awk '{print $2}'`"
			if [ "$((ro_compat&=EXT4_FEATURE_RO_COMPAT_HUGE_FILE))" != "0" -o \
				"$((ro_compat&=EXT4_FEATURE_RO_COMPAT_GDT_CSUM))" != "0" -o \
				"$((ro_compat&=EXT4_FEATURE_RO_COMPAT_DIR_NLINK))" != "0" -o \
				"$((ro_compat&=EXT4_FEATURE_RO_COMPAT_EXTRA_ISIZE))" != "0" -o \
				"$((incompat&=EXT4_FEATURE_INCOMPAT_64BIT))" != "0" -o \
				"$((incompat&=EXT4_FEATURE_INCOMPAT_MMP))" != "0" ]; then
				# ext4
				busybox sed -i 's|mount rfs '"${part}"' \([^ ]*\) .*|mount ext4 '"${part}"' \1 nosuid nodev noatime nodiratime data=writeback nobh errors=continue|g' /*.rc
			else
				# ext3
				busybox sed -i 's|mount rfs '"${part}"' \([^ ]*\) .*|mount ext3 '"${part}"' \1 nosuid nodev noatime nodiratime errors=continue|g' /*.rc
			fi
			FOUND_NON_RFS="true"
		fi
	fi
done

) >> /z4mod.init.log 2>&1
